// Travel Advisory Data
// Advisory Levels:
// 1 - Exercise Normal Precautions (green)
// 2 - Exercise Increased Caution (yellow)
// 3 - Reconsider Travel (orange)
// 4 - Do Not Travel (red)

const travelAdvisories = [
  {
    country: "Japan",
    code: "JP",
    flag: "🇯🇵",
    region: "Asia",
    level: 1,
    summary: "Japan is a very safe destination with low crime rates and excellent infrastructure.",
    lastUpdated: "2025-04-10",
    tips: [
      "Carry cash as many smaller establishments don't accept credit cards.",
      "Remove shoes when entering homes and some traditional restaurants.",
      "Be prepared for earthquakes – familiarize yourself with local emergency procedures.",
      "Carry a copy of your passport at all times.",
    ],
    health: [
      "No mandatory vaccinations required.",
      "Healthcare is excellent; consider travel insurance.",
      "Tap water is safe to drink throughout the country.",
    ],
    emergency: {
      police: "110",
      ambulance: "119",
      fire: "119",
      embassy: "+81-3-3224-5000",
    },
    visa: "Visa-free for many nationalities for up to 90 days.",
    currency: "Japanese Yen (JPY)",
    language: "Japanese",
  },
  {
    country: "France",
    code: "FR",
    flag: "🇫🇷",
    region: "Europe",
    level: 2,
    summary: "France is generally safe but be aware of pickpocketing and occasional protests in major cities.",
    lastUpdated: "2025-03-22",
    tips: [
      "Beware of pickpockets in tourist areas, especially around the Eiffel Tower and on the Metro.",
      "Avoid large protest gatherings, which can occasionally turn violent.",
      "Keep valuables in a secure money belt or hotel safe.",
      "Learn a few basic French phrases – locals appreciate the effort.",
    ],
    health: [
      "No mandatory vaccinations required for most travelers.",
      "Tap water is safe to drink.",
      "Pharmacies (marked with a green cross) are widely available.",
    ],
    emergency: {
      police: "17",
      ambulance: "15",
      fire: "18",
      embassy: "+33-1-43-12-22-22",
    },
    visa: "Schengen visa required for non-EU nationals (90 days within 180-day period).",
    currency: "Euro (EUR)",
    language: "French",
  },
  {
    country: "Mexico",
    code: "MX",
    flag: "🇲🇽",
    region: "North America",
    level: 2,
    summary: "Mexico is a popular destination but crime rates vary significantly by region.",
    lastUpdated: "2025-04-15",
    tips: [
      "Research your specific destination – risk levels vary greatly by state.",
      "Avoid traveling at night in unfamiliar areas.",
      "Use official taxis or ride-sharing apps rather than hailing cabs on the street.",
      "Do not display expensive jewelry, cameras, or electronics in public.",
      "Stay in well-traveled tourist areas.",
    ],
    health: [
      "Drink bottled water only – avoid tap water.",
      "Hepatitis A and Typhoid vaccines are recommended.",
      "Use insect repellent to protect against mosquito-borne diseases.",
    ],
    emergency: {
      police: "911",
      ambulance: "911",
      fire: "911",
      embassy: "+52-55-5080-2000",
    },
    visa: "No visa required for many nationalities for tourism up to 180 days.",
    currency: "Mexican Peso (MXN)",
    language: "Spanish",
  },
  {
    country: "Brazil",
    code: "BR",
    flag: "🇧🇷",
    region: "South America",
    level: 2,
    summary: "Brazil offers incredible diversity but has areas with high crime. Exercise caution in urban areas.",
    lastUpdated: "2025-03-30",
    tips: [
      "Avoid wearing expensive jewelry or watches in public.",
      "Be cautious when using ATMs, especially at night.",
      "Avoid displaying smartphones or cameras openly on the street.",
      "Research your specific destination, as safety varies greatly by city and neighborhood.",
    ],
    health: [
      "Yellow fever vaccination is required for certain areas.",
      "Use insect repellent to protect against Zika, Dengue, and Chikungunya.",
      "Drink bottled water.",
    ],
    emergency: {
      police: "190",
      ambulance: "192",
      fire: "193",
      embassy: "+55-61-3312-7000",
    },
    visa: "Visa requirements vary by nationality. Check before traveling.",
    currency: "Brazilian Real (BRL)",
    language: "Portuguese",
  },
  {
    country: "India",
    code: "IN",
    flag: "🇮🇳",
    region: "Asia",
    level: 2,
    summary: "India is a vibrant destination with diverse culture, but be mindful of local customs and health precautions.",
    lastUpdated: "2025-04-01",
    tips: [
      "Dress modestly, especially when visiting religious sites.",
      "Be cautious of scams targeting tourists in major cities.",
      "Book transportation through reputable companies.",
      "Stay hydrated and protect yourself from the heat.",
    ],
    health: [
      "Typhoid, Hepatitis A, and Polio vaccines are recommended.",
      "Malaria prophylaxis may be needed for certain regions.",
      "Drink only bottled or purified water.",
    ],
    emergency: {
      police: "100",
      ambulance: "102",
      fire: "101",
      embassy: "+91-11-2419-8000",
    },
    visa: "e-Visa available for many nationalities.",
    currency: "Indian Rupee (INR)",
    language: "Hindi, English (official)",
  },
  {
    country: "South Africa",
    code: "ZA",
    flag: "🇿🇦",
    region: "Africa",
    level: 3,
    summary: "South Africa has high levels of crime. Exercise caution and avoid isolated areas, especially at night.",
    lastUpdated: "2025-03-15",
    tips: [
      "Avoid displaying valuables in public.",
      "Keep car doors locked and windows up while driving.",
      "Avoid walking alone at night.",
      "Use ATMs inside banks or shopping centers during daylight hours.",
      "Arrange reliable transportation through your accommodation.",
    ],
    health: [
      "No mandatory vaccinations for most entry points, but Yellow Fever required if entering from certain countries.",
      "Malaria prophylaxis recommended for some regions (Kruger National Park area, etc.).",
      "HIV is prevalent – take appropriate precautions.",
    ],
    emergency: {
      police: "10111",
      ambulance: "10177",
      fire: "10111",
      embassy: "+27-12-431-4000",
    },
    visa: "Visa-free for many nationalities. Check current requirements.",
    currency: "South African Rand (ZAR)",
    language: "11 official languages including Zulu, Xhosa, and English",
  },
  {
    country: "Ukraine",
    code: "UA",
    flag: "🇺🇦",
    region: "Europe",
    level: 4,
    summary: "Do not travel to Ukraine due to Russia's ongoing armed conflict.",
    lastUpdated: "2025-04-20",
    tips: [
      "Do not travel to Ukraine at this time.",
      "If you are currently in Ukraine, depart immediately if it is safe to do so.",
      "Monitor official government travel advisories continuously.",
      "Register with your country's embassy if you must stay.",
    ],
    health: [
      "Medical facilities are severely strained due to the conflict.",
      "Emergency services are unreliable in conflict zones.",
      "Ensure you have adequate medication supplies if you must remain.",
    ],
    emergency: {
      police: "102",
      ambulance: "103",
      fire: "101",
      embassy: "Contact your home country's embassy or consulate immediately",
    },
    visa: "N/A – Travel strongly discouraged",
    currency: "Ukrainian Hryvnia (UAH)",
    language: "Ukrainian",
  },
  {
    country: "Colombia",
    code: "CO",
    flag: "🇨🇴",
    region: "South America",
    level: 2,
    summary: "Colombia has improved significantly in safety but some areas remain dangerous due to drug trafficking.",
    lastUpdated: "2025-03-28",
    tips: [
      "Avoid border areas with Venezuela, Ecuador, and Panama.",
      "Do not travel to FARC or ELN controlled areas.",
      "Use reputable transport companies; avoid unofficial taxis.",
      "Do not accept food or drinks from strangers.",
    ],
    health: [
      "Yellow Fever vaccination recommended for certain areas.",
      "Zika virus is present; pregnant women should reconsider travel.",
      "Drink bottled water in rural areas.",
    ],
    emergency: {
      police: "112",
      ambulance: "125",
      fire: "119",
      embassy: "+57-1-275-2000",
    },
    visa: "Visa-free for many nationalities for up to 90 days.",
    currency: "Colombian Peso (COP)",
    language: "Spanish",
  },
  {
    country: "Australia",
    code: "AU",
    flag: "🇦🇺",
    region: "Oceania",
    level: 1,
    summary: "Australia is a very safe destination with world-class infrastructure and low crime rates.",
    lastUpdated: "2025-02-14",
    tips: [
      "Be aware of dangerous wildlife including snakes, spiders, and jellyfish.",
      "Observe beach safety flags and never swim outside designated areas.",
      "Protect yourself from the sun – UV radiation is very high.",
      "Bushfire season (Oct–Apr) can disrupt travel in some regions.",
    ],
    health: [
      "No mandatory vaccinations required.",
      "Tap water is safe to drink throughout the country.",
      "Healthcare is excellent; reciprocal agreements exist for some nationalities.",
    ],
    emergency: {
      police: "000",
      ambulance: "000",
      fire: "000",
      embassy: "+61-2-6214-5600",
    },
    visa: "e-Visa (ETA) required for most nationalities.",
    currency: "Australian Dollar (AUD)",
    language: "English",
  },
  {
    country: "Egypt",
    code: "EG",
    flag: "🇪🇬",
    region: "Africa",
    level: 2,
    summary: "Egypt is generally safe for tourists in main destinations but the Sinai Peninsula remains risky.",
    lastUpdated: "2025-04-05",
    tips: [
      "Avoid the North Sinai region entirely.",
      "Be respectful of local customs and dress modestly.",
      "Only use registered tour operators.",
      "Be cautious of scams around major tourist sites.",
    ],
    health: [
      "Hepatitis A and Typhoid vaccines are recommended.",
      "Drink bottled water only.",
      "Use insect repellent in rural areas.",
    ],
    emergency: {
      police: "122",
      ambulance: "123",
      fire: "180",
      embassy: "+20-2-2797-3300",
    },
    visa: "Visa on arrival or e-Visa available for most nationalities.",
    currency: "Egyptian Pound (EGP)",
    language: "Arabic",
  },
  {
    country: "Germany",
    code: "DE",
    flag: "🇩🇪",
    region: "Europe",
    level: 1,
    summary: "Germany is a safe destination with excellent infrastructure and very low crime rates.",
    lastUpdated: "2025-02-28",
    tips: [
      "Beware of pickpockets in busy tourist areas and on public transport.",
      "Validate your public transport ticket – inspectors do check.",
      "Carry an ID document with you at all times.",
      "Tipping is customary but not mandatory (round up or add ~10%).",
    ],
    health: [
      "No mandatory vaccinations required.",
      "Tap water is safe to drink.",
      "Healthcare is excellent.",
    ],
    emergency: {
      police: "110",
      ambulance: "112",
      fire: "112",
      embassy: "+49-30-83050",
    },
    visa: "Schengen visa required for non-EU nationals.",
    currency: "Euro (EUR)",
    language: "German",
  },
  {
    country: "Thailand",
    code: "TH",
    flag: "🇹🇭",
    region: "Asia",
    level: 1,
    summary: "Thailand is one of the most popular tourist destinations in Asia with a vibrant culture and cuisine.",
    lastUpdated: "2025-03-10",
    tips: [
      "Respect the monarchy – public criticism is a criminal offense.",
      "Dress modestly when visiting temples (cover shoulders and knees).",
      "Be wary of tuk-tuk and taxi scams in Bangkok.",
      "Avoid protests and political gatherings.",
    ],
    health: [
      "Hepatitis A and Typhoid vaccines are recommended.",
      "Malaria risk in some border areas – consult a doctor.",
      "Drink bottled water.",
    ],
    emergency: {
      police: "191",
      ambulance: "1669",
      fire: "199",
      embassy: "+66-2-205-4000",
    },
    visa: "Visa-free for many nationalities for up to 30 days.",
    currency: "Thai Baht (THB)",
    language: "Thai",
  },
  {
    country: "Afghanistan",
    code: "AF",
    flag: "🇦🇫",
    region: "Asia",
    level: 4,
    summary: "Do not travel to Afghanistan due to terrorism, kidnapping, and civil unrest.",
    lastUpdated: "2025-04-18",
    tips: [
      "Do not travel to Afghanistan under any circumstances.",
      "If you are in Afghanistan, leave immediately if it is safe to do so.",
      "Contact your home country's embassy for emergency assistance.",
    ],
    health: [
      "Medical facilities are extremely limited.",
      "Emergency services are largely non-functional.",
    ],
    emergency: {
      police: "119",
      ambulance: "102",
      fire: "119",
      embassy: "Consular services are severely limited – contact your home government",
    },
    visa: "N/A – Travel strongly discouraged",
    currency: "Afghan Afghani (AFN)",
    language: "Dari, Pashto",
  },
  {
    country: "United States",
    code: "US",
    flag: "🇺🇸",
    region: "North America",
    level: 1,
    summary: "The United States is generally safe, though crime levels vary significantly by city and neighborhood.",
    lastUpdated: "2025-01-15",
    tips: [
      "Research specific areas within cities before visiting.",
      "Tipping is expected in restaurants (15–20%), taxis, and hotels.",
      "Healthcare is expensive – ensure you have comprehensive travel insurance.",
      "Be aware of extreme weather events in certain regions (hurricanes, tornadoes).",
    ],
    health: [
      "No mandatory vaccinations required for most travelers.",
      "Tap water is generally safe to drink.",
      "Medical care is world-class but very expensive.",
    ],
    emergency: {
      police: "911",
      ambulance: "911",
      fire: "911",
      embassy: "Varies by nationality – contact your country's embassy in Washington D.C.",
    },
    visa: "ESTA (Electronic System for Travel Authorization) required for Visa Waiver Program countries.",
    currency: "US Dollar (USD)",
    language: "English",
  },
  {
    country: "Morocco",
    code: "MA",
    flag: "🇲🇦",
    region: "Africa",
    level: 1,
    summary: "Morocco is a safe and welcoming destination with rich culture and history.",
    lastUpdated: "2025-03-05",
    tips: [
      "Bargaining is expected in souks and markets.",
      "Dress modestly, especially in rural areas and religious sites.",
      "Be wary of unofficial 'guides' who may lead you astray.",
      "Only use licensed taxis or ride-sharing apps.",
    ],
    health: [
      "Hepatitis A and Typhoid vaccines are recommended.",
      "Drink bottled water in rural areas.",
      "Stomach issues from food are common – be cautious of street food.",
    ],
    emergency: {
      police: "19",
      ambulance: "15",
      fire: "15",
      embassy: "+212-537-76-22-65",
    },
    visa: "Visa-free for many nationalities for up to 90 days.",
    currency: "Moroccan Dirham (MAD)",
    language: "Arabic, Berber, French",
  },
  {
    country: "Venezuela",
    code: "VE",
    flag: "🇻🇪",
    region: "South America",
    level: 4,
    summary: "Do not travel to Venezuela due to crime, civil unrest, poor healthcare, and arbitrary detention.",
    lastUpdated: "2025-04-12",
    tips: [
      "Do not travel to Venezuela.",
      "If already in country, keep a low profile and limit movement.",
      "Carry minimal valuables and always be aware of your surroundings.",
      "Register with your embassy immediately.",
    ],
    health: [
      "Healthcare infrastructure has severely deteriorated.",
      "Many medications are unavailable.",
      "Bring all necessary medications and first-aid supplies.",
    ],
    emergency: {
      police: "171",
      ambulance: "171",
      fire: "171",
      embassy: "Contact your home country's embassy immediately",
    },
    visa: "N/A – Travel strongly discouraged",
    currency: "Venezuelan Bolívar (VES)",
    language: "Spanish",
  },
];

const regions = ["All Regions", "Asia", "Europe", "North America", "South America", "Africa", "Oceania"];

const advisoryLevels = {
  1: { label: "Exercise Normal Precautions", color: "#27ae60", bg: "#d5f5e3", icon: "✅" },
  2: { label: "Exercise Increased Caution", color: "#f39c12", bg: "#fef9e7", icon: "⚠️" },
  3: { label: "Reconsider Travel", color: "#e67e22", bg: "#fdebd0", icon: "🔶" },
  4: { label: "Do Not Travel", color: "#c0392b", bg: "#fadbd8", icon: "🚫" },
};
